#application.properties? ??
#server.port = 8081
#spring.datasource.url=jdbc:mariadb://localhost:3306/member
#spring.datasource.username=root
#spring.datasource.password=1234

#server:
#  port: 8081
#
#spring:
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mariadb://localhost:3306/member
#    username: root
#    password: 1234
#--- #---? ??? ???? ??
#server:
#  port: 8081
#
#spring:
#  profiles:
#    active: prod
#  datasource:
#    url: jdbc:mariadb://localhost:3307/member
#    username: root
#    password: 1234