spring:
  #  #  Controller와 jsp 사용 시에 경로와 확장자 설정
  #  #  기본 설정이 타임리프이므로, 타임리프 의존성 제거해야 jsp 사용 가능
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/views/
  #      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234
  jpa:
    database: mysql
    #    innoDB engine 사용 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    #    스키마는 사전 생성 필요
    generate-ddl: true
    hibernate: #jpa는 인터페이스, hibernate는 jpa의 구현체
      #      create 옵션은 매번 table을 drop 후 생성한다
      #      update 옵션은 변경사항만 alter를 적용한다
      #      validate는 실제DB와의 차이만을 체크한다
      #      실무에서는 update 또는 validate를 사용한다
      ddl-auto: update
    #      jpa가 자동으로 query를 실행할 때 query가 console창에 보여지도록
    show-sql: true
  #    springboot2.4 이상에서는 기본적으로 PathPatternParser를 사용하고 있는데,
  #    이는 이전 버전과 다른 경로 매칭 규칙을 가지고 있어, springfox와 같은 일부 라이브러리에서는 문제 발생
  #  http://localhost:8080/swagger-ui/
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  password: 1234